name: check arl and sid used for tests

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-cookies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'
      
      - name: Install check dependencies
        run: pip install requests
      
      - name: Check if ARL and SID cookies are valid for tests
        id: check_cookies
        continue-on-error: true
        env:
          DEEZER_ARL: ${{ secrets.TEST_DEEZER_ARL }}
          DEEZER_SID: ${{ secrets.TEST_DEEZER_SID }}
        run: python scripts/check_cookies.py
          
      - name: Install renew dependencies
        if: steps.check_cookies.outcome == 'failure'
        run: pip install undetected-chromedriver selenium setuptools PyNaCl

      - name: Renew ARL and SID cookies if needed
        id: renew_cookies
        if: steps.check_cookies.outcome == 'failure'
        env:
          DEEZER_EMAIL: ${{ secrets.TEST_DEEZER_EMAIL }}
          DEEZER_PWD: ${{ secrets.TEST_DEEZER_PWD }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python scripts/renew_cookies.py
