name: Test secret update

on: 
  push:
    branches: [38-add-workflow-to-update-sid-and-arl-used-for-tests]

permissions:
  contents: write
  secrets: write

jobs:
  check-cookies:
    runs-on: ubuntu-latest

    steps:
      # - name: Generate a token
      #   id: generate-token
      #   uses: actions/create-github-app-token@v2
      #   with:
      #     app-id: ${{ vars.APP_CLIENT_ID }}
      #     private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Write current secret in temporary file
        run: |
          echo "${{ secrets.TEST_SECRET }}" > ${{runner.temp}}/test_secret.txt

      - name: Update secret with new value
        env:
          # GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret set TEST_SECRET --body "MySuperUpdatedSecret" --repo ${{ github.repository }}

      - name: Write updated secret in temporary file
        run: |
          echo "${{ secrets.TEST_SECRET }}" >> ${{runner.temp}}/test_secret.txt

      - name: Compare secrets
        run: |
          cat ${{runner.temp}}/test_secret.txt
